services:
  nginx-01:
    image: nginx:alpine
    container_name: nginx-01
    environment:
      - TZ=Europe/Moscow
    networks:
      - monitoring-network
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/var/www/html/index.html
      
  nginx-02:
    image: nginx:alpine
    container_name: nginx-02
    environment:
      - TZ=Europe/Moscow
    networks:
      - monitoring-network
    ports:
      - 8081:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/var/www/html/index.html

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    environment:
      - TZ=Europe/Moscow
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring-network
    depends_on:
      - prometheus      

  node-exporter:
    image: prom/node-exporter:v1.8.2
    environment:
      - TZ=Europe/Moscow
    container_name: node-exporter
    networks:
       - monitoring-network
    ports:
      - 9100:9100

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: nginx-exporter
    environment:
      - TZ=Europe/Moscow
    networks:
      - monitoring-network
    command:
      - '-nginx.scrape-uri=http://nginx-01/nginx_status'
      - '-nginx.scrape-uri=http://nginx-02/nginx_status'
    ports:
      - 9113:9113

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: blackbox-exporter
    environment:
      - TZ=Europe/Moscow
    ports:
      - 9115:9115
    networks:
      - monitoring-network
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    environment:
      - TZ=Europe/Moscow
    ports:
      - 9093:9093
    networks:
      - monitoring-network
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
      - ./alertmanager/alertmanager.tmpl:/etc/alertmanager/alertmanager.tmpl
    command:
      - '--config.file=/etc/alertmanager/config.yml'

volumes:
  grafana-storage:

networks:
  monitoring-network:

